version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_alpine
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres    
    volumes:
      - pgadmin_data:/var/lib/pgadmin  

volumes:
  postgres_data:
  pgadmin_data:    